site_url: https://6co.de/
logo_url: https://6co.de/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Seiteneinstellungen'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Seitenname, name: sitename, widget: string, hint: 'Dies wird für den Seitentitel verwendet' }
          - {
              label: Seitenbeschreibung,
              name: sitedescription,
              widget: string,
              hint: 'Dies wird als beschreibender Text für Links verwendet, die auf diese Site verweisen',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{fields.createdAt}}-{{slug}}'
    preview_path: 'blog/{{fields.createdAt}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Erstellungsdatum', name: 'createdAt', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: false }
      - { label: 'Headline', name: 'title', widget: 'string', required: true }
      - { label: 'Beschreibung', name: 'description', widget: 'string', required: false }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', required: false }
  - name: 'projects'
    label: 'Projekte'
    label_singular: 'Projekt'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Kategorie',
          name: 'category',
          widget: 'select',
          default: 'website',
          options: [{ label: 'Website', value: 'website' }, { label: 'Virtual Reality', value: 'vr' }, { label: 'Advertising', value: 'advertising' }, { label: 'Digital Branding', value: 'digitalbranding' }, { label: 'Design System', value: 'designsystem' }, { label: 'Products & Platforms', value: 'productsandplatforms' }, { label: 'Commerce', value: 'commerce' }, { label: 'Social Media', value: 'socialmedia' }],
        }
      - { label: 'Headline', name: 'title', widget: 'string', required: true }
      - { label: 'Beschreibung', name: 'description', widget: 'string', required: false }
      - { label: 'Titelbild', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Bildergalerie',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'contact'
    label: 'Kontakt'
    files:
      - name: 'contact'
        label: 'Contact'
        file: content/pages/contact.md
        preview_path: about-the-project
        fields:
          - { label: 'Headline', name: 'title', widget: 'string', required: true }
          - { label: 'Beschreibung', name: 'description', widget: 'string', required: false }
          - { label: 'Titelbild', name: 'cover', widget: 'image', required: false, allow_multiple: false }
          - { label: 'Inhalt', name: 'body', widget: 'markdown', required: false }
